### PR TITLE
Version endpoint

### PR DESCRIPTION
**Pull request by michael1011**
Required by https://github.com/ExchangeUnion/xud/pull/1170

This PR adds a new REST API endpoint that allows for the version to be queried programmatically.

Example response:
```json
{
  "version": "0.100.5a1.dev157+geb2af878d"
}
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Working as advertised - nice work! :+1:

**Comment by offerm** [comment]
@michael1011 by accepting this we differ more from raiden's code.
I suggest that you open an issue with them, explain why this is needed (why???) and suggest that you submit a PR (with general solution description). You may be surprised with their response :-)

Also, to be accepted by Raiden it must come with some tests (unit, integration).

If this is urgently needed we can accept to our branch and in parallel discuss with Raiden + create tests.

**Comment by kilrau** [comment]
> explain why this is needed (why???) 

I think that's pretty clear and linked in the PR description.

> If this is urgently needed we can accept to our branch and in parallel discuss with Raiden + create tests.

I'd go this way.

**Comment by michael1011** [comment]
> by accepting this we differ more from raiden's code. 

Yes we do...

> I suggest that you open an issue with them

... but I am planning to also open a PR for the official Raiden repository. Sorry for not communicating that clearly upfront. Should I create an issue first before opening a PR? @offerm 

> explain why this is needed (why???)

For now this is just used by the `getinfo` PR of @rsercano: https://github.com/ExchangeUnion/xud/pull/1170
But in the long term we will need a way to query the Raiden version to determine whether it is compatible with XUD (like Raiden does with GETH). This is not an issue right now because our branch has to be used anyways but once there are multiple Raiden versions in production, it will get critical.

> If this is urgently needed we can accept to our branch and in parallel discuss with Raiden + create tests.

Up to the judgement of @kilrau.

**Comment by kilrau** [comment]
Thanks for the extended explanation @michael1011 

> > If this is urgently needed we can accept to our branch and in parallel discuss with Raiden + create tests.
> 
> Up to the judgement of @kilrau.

Yes, I'd first accept to our branch and in parallel open a PR against raiden develop, discuss with them, create tests etc.

**Review by kilrau — APPROVED** [review]

**Pull request merged**
